swagger:
  app: 'Event Booking 2.0'
  description: 'A simple event booking built with Spring Boot'
  developer: 'Emina Dedić'
  email: 'emina.dedic@stu.ibu.edu.ba'

mailsender:
  default: 'mailgun'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017  # Update the MongoDB port to 27017 (default MongoDB port)
      database: librarydb

  mailgun:
    domain: 'https://app.mailgun.com/app/sending/domains/sandbox49404f0a816543f3886cf3766fed3cee.mailgun.org'
    from-email: 'Event Booking System <mailgun@sandbox49404f0a816543f3886cf3766fed3cee.mailgun.org>'
    username: 'api'
    password: '558b23476958d4d149e86c6616786f20-3750a53b-bf41751a'
